(()=>{
'use strict';
const root=document.querySelector('main');if(!root)return;
const css=document.createElement('link');css.rel='stylesheet';css.href='/features.css?v=20261009-save-menu';document.head.append(css);
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n};
const key='hlpb-saved-v1';let saved=[];let storageOK=true;try{saved=JSON.parse(localStorage.getItem(key)||'[]');if(!Array.isArray(saved))saved=[];saved=saved.filter(x=>x&&typeof x.url==='string'&&/^\/(articles|news|events)\/[a-z0-9-]+\.html$/.test(x.url));}catch{storageOK=false}
const status=el('p','','hlpb-tool-status');status.setAttribute('role','status');
const toolbar=el('div',null,'hlpb-tools');toolbar.setAttribute('aria-label','搜尋與收藏');
const search=el('button','搜尋全站 🔍');const collection=el('button','我的收藏 ☆');search.type=collection.type='button';
function headerIcon(button,label,path){button.replaceChildren();button.setAttribute('aria-label',label);button.title=label;const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('aria-hidden','true');const shape=document.createElementNS('http://www.w3.org/2000/svg','path');shape.setAttribute('d',path);svg.append(shape);button.append(svg,el('span',label,'hlpb-header-label'))}
headerIcon(search,'搜尋全站','M10.5 3a7.5 7.5 0 1 0 0 15 7.5 7.5 0 0 0 0-15M16 16l5 5');headerIcon(collection,'我的收藏','M6 3h12v18l-6-4-6 4z');
toolbar.classList.add('hlpb-header-tools');toolbar.append(search,collection);const header=document.querySelector('.site-header');if(header)header.append(toolbar);else root.prepend(toolbar);status.classList.add('hlpb-sr-status');root.prepend(status);
let indexPromise;function index(){return indexPromise||(indexPromise=fetch('/search-index.json?v=20261009-1').then(r=>{if(!r.ok)throw Error();return r.json()}).catch(e=>{indexPromise=null;throw e}))}
function dialog(title){const d=el('dialog',null,'hlpb-tools-dialog');const h=el('h2',title);h.id='hlpb-tools-title';d.setAttribute('aria-labelledby',h.id);const close=el('button','關閉','hlpb-dialog-close');close.type='button';d.append(h,close);const previous=document.activeElement;close.onclick=()=>d.close();d.onclose=()=>{d.remove();previous?.focus()};document.body.append(d);d.showModal();return d}
function result(row){const box=el('li',null,'hlpb-search-result');const a=el('a',row.title);a.href=row.url;box.append(el('span',row.type||'文章','hlpb-result-type'),a);if(row.summary)box.append(el('p',row.summary));return box}
search.onclick=async()=>{const d=dialog('搜尋 HLPB');const label=el('label','輸入想找的主題、場地或賽事');label.htmlFor='hlpb-search';const field=el('input');field.id='hlpb-search';field.type='search';field.placeholder='例如：太昌、發球、球拍';const filters=el('select');filters.setAttribute('aria-label','內容類型');for(const t of ['全部','文章','場地','消息','賽事','頁面']){const o=el('option',t);o.value=t;filters.append(o)}const count=el('p','正在載入搜尋資料…');count.setAttribute('role','status');const list=el('ul',null,'hlpb-search-results');d.append(label,field,filters,count,list);field.focus();try{const rows=await index();function update(){list.replaceChildren();const terms=field.value.trim().toLocaleLowerCase().split(/\s+/).filter(Boolean);if(!terms.length){count.textContent='輸入關鍵字後搜尋，也可選擇內容類型。';return}const found=rows.filter(x=>(filters.value==='全部'||x.type===filters.value)&&terms.every(t=>(x.title+' '+x.summary+' '+x.text).toLocaleLowerCase().includes(t))).sort((a,b)=>Number(b.title.toLocaleLowerCase().includes(terms[0]))-Number(a.title.toLocaleLowerCase().includes(terms[0])));count.textContent=found.length?`找到 ${found.length} 筆資料`:'找不到符合的資料，試試縮短關鍵字。';found.forEach(x=>list.append(result(x)))}field.oninput=update;filters.onchange=update;update()}catch{count.textContent='搜尋資料暫時無法載入，請關閉後重試。'}};
collection.onclick=()=>{const d=dialog('我的收藏');d.append(el('p','收藏保存在這台裝置的瀏覽器，不需要登入。清除瀏覽資料或換裝置後不會保留。'));const list=el('ul',null,'hlpb-search-results');d.append(list);function render(){list.replaceChildren();if(!saved.length){list.append(el('li','還沒有收藏。開啟文章、消息或賽事詳頁，點「收藏這篇」即可加入。'));return}saved.forEach(row=>{const item=result(row);const remove=el('button','移除收藏');remove.type='button';remove.onclick=()=>{const next=saved.filter(x=>x.url!==row.url);try{localStorage.setItem(key,JSON.stringify(next));saved=next;render();refreshSave();refreshCards()}catch{status.textContent='這個瀏覽器無法儲存收藏。'}};item.append(remove);list.append(item)})}render()};
let saveButton;function refreshSave(){if(saveButton){const active=saved.some(x=>x.url===location.pathname);saveButton.textContent=active?'已收藏 ★':'收藏這篇 ☆';saveButton.setAttribute('aria-pressed',String(active))}}
if(/^\/(articles|news|events)\/[a-z0-9-]+\.html$/.test(location.pathname)){saveButton=el('button');saveButton.type='button';const articleTools=el('div',null,'hlpb-tools hlpb-article-tools');articleTools.append(saveButton);root.prepend(articleTools);refreshSave();saveButton.onclick=()=>{if(!storageOK){status.textContent='這個瀏覽器無法儲存收藏，請使用一般瀏覽模式。';return}const url=location.pathname;const next=saved.some(x=>x.url===url)?saved.filter(x=>x.url!==url):[...saved,{url,title:root.querySelector('h1')?.textContent.trim()||document.title,type:'收藏'}];try{localStorage.setItem(key,JSON.stringify(next));saved=next;refreshSave();status.textContent=saved.some(x=>x.url===url)?'已加入收藏':'已移除收藏'}catch{status.textContent='收藏未儲存，瀏覽器可能限制儲存空間。'}};
 const article=root.querySelector('.article-detail');const headings=article?[...article.querySelectorAll('h2,h3')].filter(h=>!h.closest('.article-neighbors')):[];if(headings.length>=2){const toc=el('details',null,'hlpb-toc');toc.append(el('summary','文章目錄 · 點選段落快速閱讀'));const links=el('ol');headings.forEach((h,i)=>{if(!h.id)h.id='reading-section-'+i;const li=el('li',null,h.tagName==='H3'?'hlpb-toc-sub':'');const a=el('a',h.textContent);a.href='#'+h.id;li.append(a);links.append(li)});toc.append(links);article.prepend(toc)}}
function cardSaves(){root.querySelectorAll('.article-card').forEach(card=>{if(card.querySelector('.hlpb-card-save'))return;const link=card.querySelector('a[href*="articles/"]');if(!link)return;const url=new URL(link.href,location.href).pathname;if(!/^\/articles\/[a-z0-9-]+\.html$/.test(url))return;const button=el('button',null,'hlpb-card-save');button.type='button';button.dataset.saveUrl=url;function update(){const active=saved.some(x=>x.url===url);button.textContent=active?'已收藏 ★':'收藏 ☆';button.setAttribute('aria-pressed',String(active))}update();button.onclick=()=>{const next=saved.some(x=>x.url===url)?saved.filter(x=>x.url!==url):[...saved,{url,title:card.querySelector('h2')?.textContent.trim()||link.textContent,type:'文章'}];try{localStorage.setItem(key,JSON.stringify(next));saved=next;refreshSave();refreshCards();status.textContent='收藏已更新'}catch{button.textContent='無法儲存收藏';status.textContent='瀏覽器無法儲存收藏，請使用一般瀏覽模式。'}};link.after(button)})}
function refreshCards(){root.querySelectorAll('[data-save-url]').forEach(button=>{const active=saved.some(x=>x.url===button.dataset.saveUrl);const text=active?'已收藏 ★':'收藏 ☆';if(button.textContent!==text)button.textContent=text;button.setAttribute('aria-pressed',String(active))})}
cardSaves();const articleList=root.querySelector('#article-list');if(articleList)new MutationObserver(()=>cardSaves()).observe(articleList,{childList:true,subtree:true});
if(location.pathname.endsWith('/beginners.html')){const section=el('section',null,'hlpb-reading-path');section.setAttribute('aria-labelledby','hlpb-path-title');const h=el('h2','第一次接觸？照這個順序看');h.id='hlpb-path-title';section.append(h,el('p','不用一次看完，從你現在需要的那一步開始。'));const list=el('ol');const steps=[['先認識玩法','了解匹克球用什麼器材、怎麼開始玩。','/articles/what-is-pickleball-hualien-beginners.html'],['再看基本規則','發球、雙彈規則、廚房區與計分。','#beginner-rules'],['找參與方式','先確認球局的程度、地點與報名方式。','/groups.html'],['確認場地資訊','看球網、照明與使用規定，學校場地須先洽詢。','/courts.html'],['有需要再選器材','先了解重量、握把與預算，再看詳細文章。','/gear.html']];steps.forEach(([title,desc,url])=>{const li=el('li');const a=el('a',title);a.href=url;li.append(a,el('p',desc));list.append(li)});section.append(list);const hero=root.querySelector('.page-hero');if(hero)hero.after(section);else root.append(section)}
})();
