import re,json
from pathlib import Path
p=Path('index.html');s=p.read_text()
title='花蓮匹克球資訊站 HLPB｜球場、揪球、比賽與新手指南'
desc='HLPB 花蓮匹克球資訊站：查花蓮球場設備與使用限制、找球友和球局、看花蓮匹克球比賽，以及基本規則、新手教學與球具指南。'
s=re.sub(r'<title>.*?</title>',f'<title>{title}</title>',s)
for attr,key,val in [('name','description',desc),('property','og:title',title),('property','og:description',desc),('name','twitter:title',title),('name','twitter:description',desc)]:
 s=re.sub(f'<meta {attr}="{key}" content="[^"]*">',f'<meta {attr}="{key}" content="{val}">',s)
graph={'@context':'https://schema.org','@graph':[{'@type':'WebSite','@id':'https://hlpb.com.tw/#website','name':'花蓮匹克球資訊站','alternateName':['HLPB','HLPB 花蓮匹克球資訊站'],'url':'https://hlpb.com.tw/','inLanguage':'zh-Hant','description':desc,'publisher':{'@id':'https://hlpb.com.tw/#organization'}},{'@type':'Organization','@id':'https://hlpb.com.tw/#organization','name':'HLPB 花蓮匹克球資訊站','url':'https://hlpb.com.tw/','logo':{'@type':'ImageObject','url':'https://hlpb.com.tw/assets/hlpb-logo.png'},'areaServed':{'@type':'AdministrativeArea','name':'花蓮縣'}},{'@type':'WebPage','@id':'https://hlpb.com.tw/#webpage','url':'https://hlpb.com.tw/','name':title,'isPartOf':{'@id':'https://hlpb.com.tw/#website'},'about':{'@id':'https://hlpb.com.tw/#organization'},'inLanguage':'zh-Hant'}]}
s=re.sub(r'<script type="application/ld\+json">[\s\S]*?</script>','<script type="application/ld+json">'+json.dumps(graph,ensure_ascii=False)+'</script>',s,count=1)
section='''<section class="section home-start" aria-labelledby="home-start-title"><div class="section-heading"><h2 id="home-start-title">在花蓮，怎麼開始打匹克球？</h2><p>先認識玩法，再找適合的場地與球友。</p></div><div class="home-start-grid"><div><h3>匹克球是什麼？</h3><p>使用實心球拍與有孔塑膠球，單打或雙打都能玩。第一次接觸，先看發球、雙彈規則、廚房區與計分方式。</p><a class="text-link" href="articles/what-is-pickleball-hualien-beginners.html">認識匹克球玩法</a></div><div><h3>花蓮哪裡可以打？</h3><p>球場列表整理公共與校園場地、室內球館的球網和照明。學校場地沒有對外自由開放，須先洽學校或租借團體。</p><a class="text-link" href="courts.html">查看花蓮匹克球場</a></div><div><h3>一個人也能找球局嗎？</h3><p>可從公開球局、協會消息與社群連結找起。報名前確認地點、程度、人數與參加方式。</p><a class="text-link" href="groups.html">找花蓮匹克球球友</a></div></div></section>'''
if 'home-start-title' not in s:s=s.replace('<section class="section about-intro"',section+'<section class="section about-intro"')
p.write_text(s)
css=Path('style.css');css.write_text(css.read_text()+'''\n/* Reader-facing topic directory and contextual links. */\n.article-topic-directory,.related-reading{margin-top:30px;border-top:1px solid #9ab6b5;padding-top:24px}.article-topic-directory h2,.related-reading h2{font-size:22px}.article-topic-directory>div,.home-start-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.article-topic-directory details{padding:12px 16px;background:#f8f3e9;border:1px solid #b7c8c3}.article-topic-directory summary{cursor:pointer;font-weight:700}.article-topic-directory li,.related-reading li{margin:10px 0}.article-topic-directory a,.related-reading a{text-decoration:underline;text-underline-offset:3px}.home-start-grid{grid-template-columns:repeat(3,minmax(0,1fr));gap:28px}.home-start-grid h3{font-size:22px;line-height:1.4}.home-start-grid p{font-size:15px}.gear-illustration{display:block;width:100%;height:auto;aspect-ratio:16/9;object-fit:contain;margin-bottom:18px}.guide-card:has(.gear-illustration){overflow:hidden}\n@media(max-width:700px){.article-topic-directory>div,.home-start-grid{grid-template-columns:1fr}.home-start-grid h3{font-size:19px}}\n''')
